name: Deploy to AWS S3
run-name: Deploy to AWS S3
on:
  #workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync . ${{ vars.AWS_S3_BUCKET_NAME }} --delete --exclude '.git/*' --exclude '.github/*' --exclude '*.DS_Store*'